export const cellObject = {
	value: null,
	notes: {
		1: { corner: false, center: false },
		2: { corner: false, center: false },
		3: { corner: false, center: false },
		4: { corner: false, center: false },
		5: { corner: false, center: false },
		6: { corner: false, center: false },
		7: { corner: false, center: false },
		8: { corner: false, center: false },
		9: { corner: false, center: false },
	},
};

export const boardArray = [
	[
		cellObject,
		cellObject,
		cellObject,
		cellObject,
		cellObject,
		cellObject,
		cellObject,
		cellObject,
		cellObject,
	],
	[
		cellObject,
		cellObject,
		cellObject,
		cellObject,
		cellObject,
		cellObject,
		cellObject,
		cellObject,
		cellObject,
	],
	[
		cellObject,
		cellObject,
		cellObject,
		cellObject,
		cellObject,
		cellObject,
		cellObject,
		cellObject,
		cellObject,
	],
	[
		cellObject,
		cellObject,
		cellObject,
		cellObject,
		cellObject,
		cellObject,
		cellObject,
		cellObject,
		cellObject,
	],
	[
		cellObject,
		cellObject,
		cellObject,
		cellObject,
		cellObject,
		cellObject,
		cellObject,
		cellObject,
		cellObject,
	],
	[
		cellObject,
		cellObject,
		cellObject,
		cellObject,
		cellObject,
		cellObject,
		cellObject,
		cellObject,
		cellObject,
	],
	[
		cellObject,
		cellObject,
		cellObject,
		cellObject,
		cellObject,
		cellObject,
		cellObject,
		cellObject,
		cellObject,
	],
	[
		cellObject,
		cellObject,
		cellObject,
		cellObject,
		cellObject,
		cellObject,
		cellObject,
		cellObject,
		cellObject,
	],
	[
		cellObject,
		cellObject,
		cellObject,
		cellObject,
		cellObject,
		cellObject,
		cellObject,
		cellObject,
		cellObject,
	],
];
